name: corelabchallenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  firebase_messaging: ^15.1.3
  english_words: ^4.0.0
  brasil_fields: ^1.15.0
  loading_animation_widget: ^1.2.1
  awesome_snackbar_content: ^0.1.4
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  diacritic: ^0.1.6
  adaptive_action_sheet: ^2.0.3
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/  

  fonts:
    - family: DMSans
      fonts:
        - asset: assets\fonts\DMSans-Thin.ttf
          weight: 100
        - asset: assets\fonts\DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\DMSans-Light.ttf
          weight: 300
        - asset: assets\fonts\DMSans-Regular.ttf
          style: normal
        - asset: assets\fonts\DMSans-Medium.ttf
          weight: 500
        - asset: assets\fonts\DMSans-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\DMSans-Bold.ttf
          weight: 700
        - asset: assets\fonts\DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\DMSans-Black.ttf
          weight: 900  
